package com.jay.ai;

import android.Manifest; import android.content.Context; import android.content.Intent; import android.content.pm.PackageManager; import android.hardware.camera2.CameraCharacteristics; import android.hardware.camera2.CameraManager; import android.location.Location; import android.location.LocationManager; import android.media.AudioManager; import android.net.ConnectivityManager; import android.net.NetworkCapabilities; import android.net.Uri; import android.provider.MediaStore; import android.provider.Settings; import java.text.DateFormat; import java.text.SimpleDateFormat; import java.util.Date; import java.util.Locale; import java.util.regex.Matcher; import java.util.regex.Pattern;

public final class JayLocalCommandManager {
 private final Context context; private final JayAppManager appManager; private final JayContactManager contactManager; private final JayCallManager callManager; private final JayMpesaManager mpesaManager;
 public JayLocalCommandManager(Context c){context=c.getApplicationContext();appManager=new JayAppManager(context);contactManager=new JayContactManager(context);callManager=new JayCallManager(context);mpesaManager=new JayMpesaManager(context);}
 public String handle(String input){if(input==null||input.trim().isEmpty())return null;String original=input.trim(),text=original.toLowerCase(Locale.ROOT);
  if(isTime(text))return "The time is "+DateFormat.getTimeInstance(DateFormat.SHORT,Locale.getDefault()).format(new Date())+".";
  if(isDate(text))return "Today is "+new SimpleDateFormat("EEEE, d MMMM yyyy",Locale.getDefault()).format(new Date())+".";
  if(text.equals("internet status")||text.equals("internet")||text.equals("network status")||text.equals("network")||text.equals("net"))return networkStatus();
  if(contains(text,"battery","bata","beteri"))return JayDeviceTools.getBattery(context)+".";
  if(contains(text,"network speed","internet speed","speed ya network"))return JayDeviceTools.getNetwork(context)+"\n"+JayDeviceTools.getNetworkSpeed(context);
  if(contains(text,"network information","network info","net info"))return JayDeviceTools.getNetwork(context);
  if(contains(text,"m-pesa balance","mpesa balance","m pesa balance","my m-pesa balance","my mpesa balance"))return mpesaManager.getLatestBalance();
  if(contains(text,"phone information","phone info","device information","device info","about my phone"))return JayDeviceTools.getDevice(context)+"\n"+JayDeviceTools.getBattery(context)+"\n"+JayDeviceTools.getStorage(context)+"\n"+JayDeviceTools.getNetwork(context);
  if(contains(text,"my location","current location","where am i","location yangu","niko wapi","location"))return location();
  if(contains(text,"torch on","flashlight on","washa torch"))return torch(true); if(contains(text,"torch off","flashlight off","zima torch"))return torch(false);
  if(text.matches(".*\\bvolume\\s+\\d{1,3}%?.*")){Integer p=numberAfter(text,"volume");if(p!=null)return volume(p);}
  String bg=background(text);if(bg!=null)return bg;
  if(text.contains("settings")&&text.contains("developer"))return openSettings(Settings.ACTION_APPLICATION_DEVELOPMENT_SETTINGS); if(contains(text,"open settings","open phone settings","fungua settings","fungua mipangilio"))return openSettings(Settings.ACTION_SETTINGS);
  if(contains(text,"open camera","open the camera","fungua camera","fungua kamera"))return openCamera();
  if(text.contains("whatsapp")&&(text.contains("text ")||text.contains("message ")||text.contains("send ")))return whatsappMessage(original);
  if(text.startsWith("call "))return callContact(original.substring(5).trim());
  if(text.startsWith("open ")){String app=original.substring(5).trim();String r=appManager.openApp(app);if(r.startsWith("OPENED_APP:"))return "Opening "+r.substring(11)+".";return r;}
  return null;
 }
 private boolean isTime(String t){return t.equals("time")||t.equals("what time")||t.equals("time now")||t.equals("what is the time")||t.equals("what's the time")||t.equals("what time is it")||t.contains("current time")||t.contains("saa ngapi")||t.contains("saa ni ngapi");}
 private boolean isDate(String t){return t.equals("today")||t.equals("what is today")||t.equals("when is today")||t.equals("date")||t.equals("what date is it")||t.equals("leo ni lini")||t.equals("leo ni tarehe gani")||t.contains("today's date")||t.contains("what day is today");}
 private String networkStatus(){try{ConnectivityManager cm=(ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);if(cm==null)return "Network information is unavailable.";NetworkCapabilities n=cm.getNetworkCapabilities(cm.getActiveNetwork());if(n==null)return "The phone is not currently connected to a network.";String type=n.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)?"Wi-Fi":n.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)?"mobile data":n.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)?"Ethernet":"network";return "Internet is connected through "+type+".";}catch(Exception e){return "I couldn't read the network status.";}}
 private String location(){if(context.checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED&&context.checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED)return "LOCATION_PERMISSION_REQUIRED";try{LocationManager m=(LocationManager)context.getSystemService(Context.LOCATION_SERVICE);Location best=null;for(String p:new String[]{LocationManager.GPS_PROVIDER,LocationManager.NETWORK_PROVIDER,LocationManager.PASSIVE_PROVIDER})try{Location l=m.getLastKnownLocation(p);if(l!=null&&(best==null||l.getTime()>best.getTime()))best=l;}catch(Exception ignored){}return best==null?"I don't have a recent location fix yet.":String.format(Locale.US,"Your last known location is latitude %.6f, longitude %.6f.",best.getLatitude(),best.getLongitude());}catch(Exception e){return "I couldn't read your location.";}}
 private String background(String t){if(contains(t,"change wallpaper","set wallpaper","wallpaper","badilisha wallpaper")){try{Intent i=new Intent(Intent.ACTION_SET_WALLPAPER).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);context.startActivity(i);return "Opening the wallpaper selector.";}catch(Exception e){return "I couldn't open the wallpaper selector.";}}if(contains(t,"restore default background","reset background","default background")){JayAppearanceManager.reset(context);return "Jay's default background has been restored.";}if(contains(t,"change background","background color","background colour","make the background")||t.startsWith("now to ")){String c=null;Matcher h=Pattern.compile("#[0-9a-f]{6}|#[0-9a-f]{8}",Pattern.CASE_INSENSITIVE).matcher(t);if(h.find())c=h.group();for(String x:new String[]{"black","blue","purple","red","green","cyan","dark","default"})if(t.contains(x))c=x;if(c==null&&t.startsWith("now to "))c=t.substring(7).trim();if(c==null)return "Tell me the background color you want.";return JayAppearanceManager.setBackgroundColor(context,c)?"Jay's background color is now "+c+".":"I don't recognize that background color.";}return null;}
 private String whatsappMessage(String original){String l=original.toLowerCase(Locale.ROOT);int p=l.indexOf("text "),n=5;if(p<0){p=l.indexOf("message ");n=8;}if(p<0){p=l.indexOf("send ");n=5;}if(p<0)return null;String[]a=original.substring(p+n).trim().split("\\s+",2);if(a.length<2)return "What message should I prepare?";String found=contactManager.findPhoneNumber(a[0]);if("PERMISSION_REQUIRED".equals(found))return "Contacts permission is required.";if(!found.startsWith("CONTACT_FOUND|"))return "I couldn't find a contact named "+a[0]+".";String[]d=found.split("\\|",3);try{String num=d[2].replaceAll("[^0-9+]","");if(num.startsWith("+"))num=num.substring(1);Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+num+"?text="+Uri.encode(a[1])));i.setPackage("com.whatsapp");i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);context.startActivity(i);return "Opening WhatsApp with a message to "+d[1]+". Please confirm/send it in WhatsApp.";}catch(Exception e){return "I couldn't open that WhatsApp conversation.";}}
 private String torch(boolean on){try{CameraManager m=(CameraManager)context.getSystemService(Context.CAMERA_SERVICE);for(String id:m.getCameraIdList()){CameraCharacteristics c=m.getCameraCharacteristics(id);if(Boolean.TRUE.equals(c.get(CameraCharacteristics.FLASH_INFO_AVAILABLE))){m.setTorchMode(id,on);return on?"Torch turned on.":"Torch turned off.";}}}catch(Exception ignored){}return "I couldn't control the torch.";}
 private String volume(int p){p=Math.max(0,Math.min(100,p));AudioManager a=(AudioManager)context.getSystemService(Context.AUDIO_SERVICE);if(a==null)return "I couldn't access volume.";int max=a.getStreamMaxVolume(AudioManager.STREAM_MUSIC);a.setStreamVolume(AudioManager.STREAM_MUSIC,Math.round(max*p/100f),0);return "Media volume set to "+p+"%.";}
 private Integer numberAfter(String t,String key){Matcher m=Pattern.compile("\\b"+key+"\\s+(\\d{1,3})%?").matcher(t);return m.find()?Integer.valueOf(m.group(1)):null;}
 private String openSettings(String a){try{Intent i=new Intent(a).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);context.startActivity(i);return "Opening Settings.";}catch(Exception e){return "I couldn't open Android Settings.";}}
 private String openCamera(){try{Intent i=new Intent(MediaStore.ACTION_IMAGE_CAPTURE).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);if(i.resolveActivity(context.getPackageManager())==null)return "I couldn't find a camera application.";context.startActivity(i);return "Opening the camera now.";}catch(Exception e){return "I couldn't open the camera.";}}
 private String callContact(String n){String f=contactManager.findPhoneNumber(n);if("PERMISSION_REQUIRED".equals(f))return "Contacts permission is required.";if(!f.startsWith("CONTACT_FOUND|"))return "I couldn't find a contact named "+n+".";String[]p=f.split("\\|",3);String r=callManager.callNumber(p[2]);return r.startsWith("CALL_STARTED|")?"Calling "+p[1]+".":"I couldn't start the call.";}
 private boolean contains(String t,String...w){for(String x:w)if(t.contains(x))return true;return false;}
}
